@startuml Moranguinho

    class Agricultor {
    string: nome
    cpf: identification
    email: email_x
    string: telefone
    file: foto

    }



    class Propriedade {
    string: nome
    string: distrito

    Agricultor: agricultor
    }



@enduml
