import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { SPARKGeneratedModule, SPARKGeneratedSharedModule } from './generated/module.js';
import { SPARKValidator, registerValidationChecks } from './s-p-a-r-k-validator.js';
import { CustomScopeComputation } from './r-2-d-3-scope.js';
/**
 * Declaration of custom services - add your own service classes here.
 */
export type SPARKAddedServices = {
    validation: {
        SPARKValidator: SPARKValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type SPARKServices = LangiumServices & SPARKAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const SPARKModule: Module<SPARKServices, PartialLangiumServices & SPARKAddedServices> = {
    references:{
        ScopeComputation: (services) => new CustomScopeComputation(services)
    },
    validation: {
        SPARKValidator: () => new SPARKValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createSPARKServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    SPARK: SPARKServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        SPARKGeneratedSharedModule
    );
    const SPARK = inject(
        createDefaultModule({ shared }),
        SPARKGeneratedModule,
        SPARKModule
    );
    shared.ServiceRegistry.register(SPARK);
    registerValidationChecks(SPARK);
    return { shared, SPARK };
}
